# Generated by Django 4.2.4 on 2023-08-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("author", models.CharField(max_length=30)),
                ("year", models.CharField(max_length=4)),
                ("des", models.CharField(max_length=100)),
            ],
        ),
    ]
