# Generated by Django 4.2.4 on 2023-08-12 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lib_user", "0003_renewal"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=50)),
                ("author_name", models.CharField(max_length=30)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "book_add_time",
                    models.TimeField(
                        default=datetime.datetime(
                            2023, 8, 12, 12, 9, 52, 850706, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("book_add_date", models.DateField(default=datetime.date(2023, 8, 12))),
            ],
            options={"unique_together": {("book_name", "author_name")},},
        ),
        migrations.CreateModel(
            name="IssuedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_date", models.DateField(default=datetime.date(2023, 8, 12))),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "book_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lib_user.book"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lib_user.lib_user",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="renewal", name="book",),
        migrations.RemoveField(model_name="renewal", name="user",),
        migrations.DeleteModel(name="Add_Book",),
        migrations.DeleteModel(name="Renewal",),
    ]
