# Generated by Django 4.2.4 on 2023-08-12 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_user", "0004_book_issueditem_remove_renewal_book_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_add_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 8, 12, 12, 15, 55, 534609, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
