# Generated by Django 4.2.4 on 2023-08-12 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_user", "0008_alter_book_book_add_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_add_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 8, 12, 19, 35, 51, 716379, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
