# Generated by Django 4.2.4 on 2023-08-13 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lib_user", "0011_alter_book_book_add_time_alter_issueditem_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_add_time",
            field=models.TimeField(
                default=datetime.datetime(
                    2023, 8, 13, 13, 41, 31, 628897, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
